[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ah_workspace"
version = "1.0.0"
description = "Adds a workspace area between file tree and chat"
authors = [{name = "Assistant"}]
